version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    open-pull-requests-limit: 3
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    directories:
      - "/"
      - "**/rootfs"
    schedule:
      interval: "weekly"
      day: "sunday"
    open-pull-requests-limit: 3
    groups:
      go-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directories:
      - "**/rootfs"
    schedule:
      interval: "weekly"
      day: "sunday"
    open-pull-requests-limit: 3
    groups:
      docker-images:
        patterns:
          - "*"
